### ISSUE TITLE
Renewable Energy Sliders

### ISSUE THREAD

**Issue by TylerLo416** [Center-For-Energy-TEC-App/Tec-App#29]
Frontend portion of the sliders should be created. Use the version in Iteration 4 of the Figma.

- [ ] I would recommend exporting the little round icons as svg files if possible
- [ ] include the little blurb about nuclear at the end
- [ ] add the reset to global values button (which doesn't need to be implemented yet cause the backend isn't set up)
- [ ] Create the 2024 line, but the BAU and GV lines don't need to be implemented yet because they rely on the backend / data values
- [ ] Create the tooltips - tooltip text is provided in the Figma
- [ ] All the sliders should be initially set to 2024.
- [ ] Sliding the sliders around shouldn't do anything yet (because it relies on the backend)
- You can take a look at the desktop Hifi to see how the global dashboard sliders should look like (there's no updated mobile version)

**Comment by yotzkim** [comment]
PR #45
